/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.Common;

import Controller.UserController;
import View.Auth.ContainerLogs;
import java.awt.BorderLayout;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author amado
 */
public class FramePrincipal extends javax.swing.JFrame {

    private String username,password;
    private String ruta;
    private UserController UC;

    public FramePrincipal() {
        this.UC = new UserController();
        ruta = "C:\\Users\\amado\\OneDrive\\Escritorio\\TAPVERANO\\Proyecto\\Proyecto\\src\\Resourses\\Confing\\ConfigInicio.txt";
        initComponents();
        if(recordarInicio(ruta)){
            Valid(username);
        }else{
            InitContent();
        }
        ejecutarTareaEnHilo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Principal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout PrincipalLayout = new javax.swing.GroupLayout(Principal);
        Principal.setLayout(PrincipalLayout);
        PrincipalLayout.setHorizontalGroup(
            PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 767, Short.MAX_VALUE)
        );
        PrincipalLayout.setVerticalGroup(
            PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 458, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    public static void InitContent() {
        ContainerLogs loginPanel = new ContainerLogs();
            if (!(Principal.getLayout() instanceof BorderLayout)) {
            Principal.setLayout(new BorderLayout());
        }
        Principal.removeAll();
        Principal.add(loginPanel,BorderLayout.CENTER);
        Principal.revalidate();
        Principal.repaint();
    }
    
    public static void Valid(String mail) {
        
        Menu loginPanel = new Menu(mail);
            if (!(Principal.getLayout() instanceof BorderLayout)) {
            Principal.setLayout(new BorderLayout());
        }
        Principal.removeAll();
        Principal.add(loginPanel,BorderLayout.CENTER);
        Principal.revalidate();
        Principal.repaint();
        
    }
    private boolean recordarInicio(String filePath) {
        
        
        try (BufferedReader reader = new BufferedReader(new FileReader(filePath))) {
            // Lee la primera línea (usuario)
            username = reader.readLine();
            
            // Lee la segunda línea (contraseña)
            password = reader.readLine();

            if (username == null || password == null) {
                throw new IOException("El archivo no contiene suficientes líneas.");
            }

            // Elimina cualquier espacio en blanco al inicio o final
            username = username.trim();
            password = password.trim();
            if(UC.login(username,password)){
                FramePrincipal.Valid(username);
                
                return true;
            }else{
                System.out.println("no valido "+username+ " "+ password);
                return false;
            }

        } catch (IOException e) {
            return false;
        }   
    }
   
    public void ejecutarTareaEnHilo() {
        Thread hilo = new Thread(new Runnable() {
            @Override
            public void run() {
                
                try {
                    while(true){
                        Thread.sleep(500000); 
                        JOptionPane.showMessageDialog(null, "Te invitamos a hcaer un pedido", "Info", JOptionPane.INFORMATION_MESSAGE);
                    }
                    

                } catch (InterruptedException e) {
                    System.out.println("El hilo fue interrumpido.");
                }
            }
        });

        hilo.start(); // Inicia el hilo
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JPanel Principal;
    // End of variables declaration//GEN-END:variables
}
